export default [
  //   { name: "key", word: "열쇠" },
  //   { name: "body", word: "신체" },
  //   { name: "code", word: "암호" },
  //   { name: "map", word: "지도" },
  //   { name: "time", word: "시각" },
  //   { name: "book", word: "책" },
  //   { name: "pause", word: "정지시키다" },
  //   { name: "mail", word: "우편" },
  //   { name: "home", word: "집" },
  //   { name: "star", word: "별" },
  //   { name: "cloud", word: "구름" },
  //   { name: "eye", word: "눈" },
  //   { name: "camera", word: "카메라" },
  //   { name: "heart", word: "마음" },
  //   { name: "calendar", word: "달력" },
  //   { name: "hourglass", word: "모래시계" },
  //   { name: "flag", word: "깃발" },
  //   { name: "car", word: "자동차" },
  //   { name: "man", word: "남성" },
  //   { name: "gift", word: "선물" },
  //   { name: "wallet", word: "지갑" },
  //   { name: "woman", word: "여성" },
  //   { name: "earth", word: "지구" },
  //   { name: "wifi", word: "와이파이" },
  //   { name: "brush", word: "브러시" },
  //   { name: "bug", word: "벌레" },
  //   { name: "clipboard", word: "클립보드" },
  //   { name: "cog", word: "장부" },
  //   { name: "compass", word: "나침반" },
  //   { name: "copy", word: "복사" },
  //   { name: "document", word: "문서" },
  //   { name: "documents", word: "서류" },
  //   { name: "grid", word: "그리드" },
  //   { name: "help", word: "돕다" },
  //   { name: "images", word: "이미지" },
  //   { name: "language", word: "언어" },
  //   { name: "layers", word: "레이어" },
  //   { name: "leaf", word: "잎" },
  //   { name: "list", word: "목록" },
  //   { name: "location", word: "위치" },
  //   { name: "lock-open", word: "잠금 해제" },
  //   { name: "log-out", word: "로그 아웃" },
  //   { name: "magnet", word: "자석" },
  //   { name: "medal", word: "메달" },
  //   { name: "megaphone", word: "메가폰" },
  //   { name: "print", word: "인쇄" },
  //   { name: "rocket", word: "로켓" },
  //   { name: "share", word: "공유하다" },
  //   { name: "shield", word: "방패" },
  //   { name: "shuffle", word: "혼합" },
  //   { name: "tv", word: "TV" },
  //   { name: "water", word: "물" },
  //   { name: "disc", word: "디스크" },
  //   { name: "eye-off", word: "눈을 떼다" },
  //   { name: "film", word: "영화" },
  //   { name: "log-in", word: "로그인" },
  //   { name: "mic-off", word: "마이크 오프" },
  //   { name: "move", word: "이동하다" },
  //   { name: "pause-circle", word: "일시 중지 원" },
  //   { name: "play-circle", word: "플레이 서클" },
  //   { name: "power", word: "힘" },
  //   { name: "repeat", word: "반복하다" },
  //   { name: "send", word: "보내다" },
  //   { name: "star-half", word: "스타 하프" },
  //   { name: "flask", word: "플라스크" },
  //   { name: "cut", word: "자르다" },
  //   { name: "medkit", word: "메드킷" },
  //   { name: "beer", word: "맥주" },
  //   { name: "female", word: "여자" },
  //   { name: "male", word: "남성" },
  //   { name: "paw", word: "발" },
  //   { name: "cube", word: "입방체" },
  //   { name: "at", word: "에" },
  //   { name: "bus", word: "버스" },
  //   { name: "bed", word: "침대" },
  //   { name: "train", word: "기차" },
  //   { name: "newspaper", word: "신문" },
  //   { name: "backspace", word: "역행 키이" },
  //   { name: "egg", word: "계란" },
  //   { name: "glasses", word: "안경" },
  //   { name: "hammer", word: "망치" },
  //   { name: "receipt", word: "영수증" },
  //   { name: "ribbon", word: "리본" },
  //   { name: "school", word: "학교" },
  //   { name: "shapes", word: "모양" },
  //   { name: "skull", word: "두개골" },
  //   { name: "navigate", word: "탐색" },
  //   { name: "person", word: "사람" },
  //   { name: "cloudy", word: "흐림" },
  //   { name: "snow", word: "눈" },
  //   { name: "bandage", word: "붕대" },
  //   { name: "alarm", word: "경보" },
  //   { name: "albums", word: "앨범" },
  //   { name: "analytics", word: "해석학" },
  //   { name: "at-circle", word: "원에서" },
  //   { name: "attach", word: "붙이다" },
  //   { name: "barbell", word: "바벨" },
  //   { name: "baseball", word: "야구" },
  //   { name: "basketball", word: "농구" },
  //   { name: "battery-dead", word: "배터리 방전" },
  //   { name: "beaker", word: "굽 달린 큰 컵" },
  //   { name: "cafe", word: "카페" },
  //   { name: "call", word: "전화" },
  //   { name: "ear", word: "귀" },
  { name: "trophy", word: "트-로-피" },
  { name: "headset", word: "헤드-폰" },
  { name: "basket", word: "바-구-니" },
  { name: "flame", word: "불-꽃" },
  { name: "bicycle", word: "자-전-거" },
  { name: "ice-cream", word: "아이스-크림" },
  // { name: "pizza", word: "피-자" },
  // { name: "planet", word: "행-성" },
  // { name: "rose", word: "장-미" },
  // { name: "shirt", word: "셔-츠" },
  // { name: "wine", word: "와-인" },
];
